# Generated by Django 3.1.3 on 2020-12-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='class',
            name='tags',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='class',
            name='title',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
