# Generated by Django 3.1.3 on 2020-12-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20201220_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='in_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_class', to='classes.class'),
        ),
    ]
