# Generated by Django 3.1.3 on 2020-12-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201117_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('MT', 'Mentee'), ('MR', 'Mentor')], default='MT', max_length=2),
        ),
    ]
