name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_SECRET}}
          heroku_app_name: "sdos-client" #Must be unique in Heroku
          heroku_email: "raghav.kukreti@gmail.com"
          appdir: "client"  
